// Builds src/data/angles.js — extra photo angles for the Wikimedia-sourced
// products (cars, watches, Apple hardware, appliances).
//
// Feedback was that photos are thin and people want more per product. Open Food
// Facts already gives 125 grocery products front/ingredients/nutrition, but the
// real-brand products had exactly one photo each. Commons usually holds several
// of the same model, which is genuinely "more photos of this product" rather
// than more photos of the category.
import fs from 'node:fs'
import { TEMPLATE_HEROES } from '../src/data/products.js'

const sleep = (ms) => new Promise((r) => setTimeout(r, ms))
const UA = { 'User-Agent': 'thodasa-angles/1.0 (bhaumik.tandan@enablix.com)' }

// A model shot is only useful if it can be read on a portrait card. Panoramas
// and thin strips contain down to nothing; see the nutrition-panel lesson.
const OK_RATIO = (w, h) => w && h && w / h >= 0.5 && w / h <= 1.9

const search = async (q, limit = 8) => {
  const u = 'https://commons.wikimedia.org/w/api.php?action=query&format=json&generator=search'
    + `&gsrsearch=${encodeURIComponent('filetype:bitmap ' + q)}&gsrlimit=${limit}&gsrnamespace=6`
    + '&prop=imageinfo&iiprop=url|size|extmetadata&iiurlwidth=960'
  for (let a = 0; a < 3; a++) {
    try {
      const r = await fetch(u, { headers: UA })
      if (r.status === 429 || r.status >= 500) { await sleep(2000 * (a + 1)); continue }
      if (!r.ok) return []
      const j = await r.json()
      return Object.values(j.query?.pages ?? {})
    } catch { await sleep(1500) }
  }
  return []
}

// only the products already carrying a verified Commons photo
const targets = TEMPLATE_HEROES.filter((p) => /upload\.wikimedia\.org/.test(p.img))
console.log(`wikimedia-sourced products: ${targets.length}`)

const out = {}
let i = 0, added = 0
for (const p of targets) {
  i++
  // baseName is the model and already includes the brand; p.name is the variant
  // ("Mahindra Thar — AX · Alpine White") and matches nothing on Commons.
  const q = String(p.baseName || '').replace(/\s+/g, ' ').trim()
  const pages = await search(q)
  const urls = [p.img] // keep the verified hero first
  for (const pg of pages) {
    const ii = pg.imageinfo?.[0]
    if (!ii?.thumburl) continue
    if (!OK_RATIO(ii.width, ii.height)) continue
    const url = ii.thumburl.split('?')[0]
    if (urls.includes(url)) continue
    urls.push(url)
    if (urls.length >= 4) break
  }
  if (urls.length > 1) { out[p.templateId] = urls; added++ }
  if (i % 10 === 0) console.log(`  ${i}/${targets.length} … ${added} now multi-angle`)
  await sleep(900)
}

fs.writeFileSync(
  'src/data/angles.js',
  '// GENERATED by scripts/fetch-angles.mjs — do not edit by hand.\n'
  + '// templateId -> [hero, ...extra Wikimedia angles of the same model]\n'
  + 'export default ' + JSON.stringify(out, null, 1) + '\n',
)
const total = Object.values(out).reduce((s, a) => s + a.length, 0)
console.log(`wrote ${added} products, ${total} photos (avg ${(total / (added || 1)).toFixed(1)})`)
